[[constraint]]
  name = "github.com/stephane-martin/vault-exec"
  version = "0.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/stephane-martin/golang-ssh"
  version = "0.5.3"

[[constraint]]
  name = "github.com/awnumar/memguard"
  version = "0.15.0"

[[constraint]]
  name = "github.com/valyala/fastjson"
  version = "1.4.1"

[prune]
  go-tests = true
  unused-packages = true
