[[constraint]]
  name = "github.com/stephane-martin/vault-exec"
  version = "0.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/stephane-martin/golang-ssh"
  version = "0.6.3"

[[constraint]]
  name = "github.com/awnumar/memguard"
  version = "0.15.0"

[[constraint]]
  name = "github.com/valyala/fastjson"
  version = "1.4.1"

[[constraint]]
  name = "github.com/stephane-martin/go-vis"
  branch = "master"

[[constraint]]
  name = "github.com/ktr0731/go-fuzzyfinder"
  version = "0.1.2"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.5"

[[constraint]]
  name = "github.com/peterh/liner"
  branch = "master"

[[constraint]]
  name = "github.com/logrusorgru/aurora"
  branch = "master"

[[constraint]]
  name = "github.com/ahmetb/go-linq"
  version = "3.0.0"

[[constraint]]
  name = "github.com/rivo/tview"
  branch = "master"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.6.3"

[[constraint]]
  name = "github.com/gabriel-vasile/mimetype"
  version = "0.3.2"

#[[constraint]]
#  name = "github.com/gobwas/glob"
#  version = "0.2.3"

[[constraint]]
  name = "github.com/scylladb/go-set"
  version = "1.0.2"

[[constraint]]
  name = "github.com/google/gops"
  version = "0.3.6"

[[constraint]]
  name = "github.com/stephane-martin/go-mimeapps"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "1.0.28"

[prune]
  go-tests = true
  unused-packages = true
