[[constraint]]
  name = "github.com/stephane-martin/vault-exec"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
